### PR TITLE
LoafWallet will now validate new and legacy P2SH address formats

### PR DESCRIPTION
**Pull request by mperklin**
**Background**
Although Loafwallet has upgraded its P2SH prefix value from 05 to 50 on mainnet (196 to 58 on testnet), many other wallets, services, and block explorers still have not.

This introduces an incompatibility where Loafwallet is unable to scan addresses and send litecoin to services/users who have not yet upgraded.

While address converters do exist, they are cumbersome to use on mobile where Loafwallet is used. They're easy to use on a desktop, but Loafwallet does not run on desktops.

**Summary**
This pull request enables Loafwallet to scan and send coins to addresses with either the new M** prefix or addresses with the legacy 3** prefix.
This change is intended to be temporary while the Litecoin community is in the middle of this transitional period.

In the future, once the majority of block explorers, wallets, and services upgrade their software to accept the new M** format, this change can be reverted so that Loafwallet only works with new M** addresses.

The following is a list of services that Loafwallet is currently incompatible with because they have not yet upgraded to new M** P2SH addresses:

**Block Explorers**
1. [BlockCypher](https://live.blockcypher.com/ltc/tx/73e1ef8ef5f02293879e5fa1abe5f40e82ab24f4a585b32127a668eb628249a6/)
2. [CryptoID](https://chainz.cryptoid.info/ltc/tx.dws?73e1ef8ef5f02293879e5fa1abe5f40e82ab24f4a585b32127a668eb628249a6.htm)
3. [explorer.litecoin.net](http://explorer.litecoin.net/tx/73e1ef8ef5f02293879e5fa1abe5f40e82ab24f4a585b32127a668eb628249a6)
4. [blockr.io](http://ltc.blockr.io/tx/info/73e1ef8ef5f02293879e5fa1abe5f40e82ab24f4a585b32127a668eb628249a6)
5. [chain.so](https://chain.so/tx/LTC/73e1ef8ef5f02293879e5fa1abe5f40e82ab24f4a585b32127a668eb628249a6)
6. [bchain.info](https://bchain.info/LTC/tx/73e1ef8ef5f02293879e5fa1abe5f40e82ab24f4a585b32127a668eb628249a6)
7. [ProHashing.com](https://prohashing.com/explorer/Litecoin/73e1ef8ef5f02293879e5fa1abe5f40e82ab24f4a585b32127a668eb628249a6/)

**Wallets**
1. [Exodus Wallet](https://www.exodus.io/)
2. [LiteVault](https://www.litevault.net/wallet/login)
3. [Coinomi](https://coinomi.com/)
4. [Jaxx](https://www.exodus.io)

**Exchanges**
1. [BitFinex](https://bitfinex.com)
2. [Kraken](https://kraken.com)
3. [Poloniex](https://poloniex.com)
4. [BitStamp](https://bitstamp.net)
5. [Coinbase](https://coinbase.com)

**Services**
1. [Coindroids](https://lite.coindroids.com)

### CODE REVIEW

**Comment by Abstrct** [comment]
I fully support the change to M addresses, but it will take time for everything to migrate over. Committing this would be a huge help in bridging the gap between 3 and M P2SH address support.

**Comment by Ben3105** [comment]
Dear mperklin, today I sent LTC from my loaf wallet to kraken. I posted my problem within the issue-section here. I am no programmer and so I do not understand why my LTC did not arrive to Kraken. Are my Litecoins gone or how can I get them back?  Thanks many times for your help! Kind regards, Ben

**Comment by losh11** [comment]
utACK - just needs further testing. I tried a similar approach earlier this year but LoafWallet was unexpectedly crashing. If everything works well, I will merge tomorrow.

**Comment by Abstrct** [comment]
Is there any update on the results of the testing?

**Comment by losh11** [comment]
Sorry for note addressing this any earlier. Working on LoafWallet v2 right now, it's all currently in another repo, but when finished, I'll create a new branch from there. A updated PR would be appreciated.

**Comment by losh11** [comment]
Closing for now. With LoafWallet v2.0 this change needs to be made on the `loafwallet-core` repo.

**Pull request closed without merging**
